
hostname = wrapper.cyapi.cn, api.caiyunapp.com, starplucker.cyapi.cn, ad.cyapi.cn

^https?:\/\/ad\.cyapi\.cn\/v\d url reject-200
^https?:\/\/wrapper\.cyapi\.cn\/v\d\/activity url reject-200
^https?:\/\/api\.caiyunapp\.com\/v\d\/activity url reject-200
^https?:\/\/starplucker\.cyapi\.cn\/v\d\/operation\/banners url reject-200
^https?:\/\/starplucker\.cyapi\.cn\/v\d\/campaigns url reject-200
